from __future__ import annotations

"""Public API of the ``efc`` (engineered-feature common) subpackage.

Re-exports all public symbols from the nine focused submodules that replaced
the monolithic engineered_feature_common.py.  Import from this package rather
than from the individual submodules to stay insulated from internal restructuring.

Submodule responsibilities:
    feature_registry    — variant registration, A-scale exponents, feature column lists.
    data_io             — I/O types (DatasetMeta, StageTables, RunArtifacts,
                          Stage1Config, Stage2Config) and merge_config.
    feature_engineering — CSV loading, A-scale transform, z-scoring, split assignment.
    models              — PenetrationMLP, sigmoid physical model.
    objectives          — Stage-1 MSE and Stage-2 NLL loss functions.
    train_loop          — dataset, dataloader, run_epoch, train_with_early_stopping.
    checkpoint          — run-dir creation, artifact saving, loss-curve plotting.
    inference           — model loading, feature matrix building, physical predictions.
"""

from .feature_registry import (
    A_SCALE_DP_EXP_BY_VARIANT,
    BASE_STATIC_FEATURE_COLUMNS,
    BASE_STATIC_ZSCORE_COLUMNS,
    DEFAULT_A_SCALE_DENSITY_EXP,
    DEFAULT_A_SCALE_DIAMETER_EXP,
    DEFAULT_A_SCALE_DP_EXP,
    DEFAULT_RUNS_ROOT,
    DEFAULT_SYNTHETIC_DATA_ROOT,
    DEFAULT_TEST_MATRIX_ROOT,
    DIAMETER_FEATURE_COLUMNS,
    DIAMETER_ZSCORE_COLUMNS,
    FEATURE_COLUMNS_BY_VARIANT,
    LEGACY_9_FEATURE_COLUMNS,
    LEGACY_FEATURE_COLUMNS,
    LEGACY_FILL_DEFAULTS,
    MIN_TIME_SHIFT_S,
    PRESSURE_FEATURE_COLUMNS,
    PRESSURE_ZSCORE_COLUMNS,
    PROJECT_ROOT,
    REFERENCE_PRESSURE_BAR,
    TARGET_SCALE_MODE_BY_VARIANT,
    TIME_FEATURE,
    ZSCORE_BASE_COLUMNS_BY_VARIANT,
    resolve_tilt_angle_radian,
    umbrella_to_tilt_radian,
)
from .data_io import (
    DEFAULT_STAGE1_CONFIG,
    DEFAULT_STAGE2_CONFIG,
    DatasetMeta,
    RunArtifacts,
    Stage1Config,
    Stage2Config,
    StageTables,
    build_dataset_registry,
    merge_config,
    normalize_dataset_key,
)
from .models import (
    FamilyAwarePenetrationMLP,
    FamilyFiLMAdapter,
    PenetrationMLP,
    RESIDUAL_FILM_ARCHITECTURE_MODES,
    ResidualFamilyAwarePenetrationMLP,
    ResidualFiLMFamilyAwarePenetrationMLP,
    build_model,
    family_head_state_dict_to_residual,
    make_activation,
    reconstruct_penetration_series,
    sigmoid,
    spray_penetration_model_sigmoid,
    spray_penetration_model_sigmoid_d_dt,
    state_dict_to_residual_film,
)
from .feature_engineering import (
    NOZZLE_NAME_TO_ID,
    REFERENCE_DENSITY_KG_M3,
    apply_a_scale_transform,
    apply_saved_scaler_state,
    apply_zscore,
    assign_splits_by_group,
    assign_splits_leave_one_out,
    build_all_stage_tables,
    build_canonical_feature_table,
    build_variant_feature_table,
    build_sample_group_id,
    canonicalize_chamber_state,
    collect_selected_rows,
    compute_a_scale,
    family_id_from_name,
    fit_zscore_params,
    infer_dataset_name_from_csv_path,
    infer_feature_family,
    iter_clean_csv_files,
    linear_density_from_pressure,
    linear_pressure_from_density,
    nozzle_id_from_name,
    run_pretrain_collapse_check,
    scaler_a_scale_dp_exp,
    scaler_target_scale_mode,
    select_filtered_rows,
    select_representative_row,
    variant_a_scale_dp_exp,
    variant_target_scale_mode,
)
from .objectives import (
    derivative_physics_penalty,
    early_time_anchor_penalties,
    onset_aux_penalty,
    split_mu_logvar,
    stage1_objective,
    stage2_objective,
)
from .train_loop import (
    PointwisePenetrationDataset,
    collate_pointwise,
    make_dataloaders,
    run_epoch,
    train_with_early_stopping,
)
from .checkpoint import (
    create_run_dir,
    plot_loss_curves,
    sanitize_config_for_json,
    save_training_outputs,
)
from .inference import (
    build_feature_matrix_np,
    build_feature_tensor_torch,
    canonicalize_raw_input,
    evaluate_physical_point_with_derivatives,
    has_run_artifacts,
    has_supported_checkpoint,
    load_run_artifacts,
    predict_physical_sweep,
    resolve_model_path,
    resolve_run_dir,
    torch_scalar,
    unwrap_state_dict,
    zscore_from_state,
)

__all__ = [
    # feature_registry
    "A_SCALE_DP_EXP_BY_VARIANT",
    "BASE_STATIC_FEATURE_COLUMNS",
    "BASE_STATIC_ZSCORE_COLUMNS",
    "DEFAULT_A_SCALE_DENSITY_EXP",
    "DEFAULT_A_SCALE_DIAMETER_EXP",
    "DEFAULT_A_SCALE_DP_EXP",
    "DEFAULT_RUNS_ROOT",
    "DEFAULT_SYNTHETIC_DATA_ROOT",
    "DEFAULT_TEST_MATRIX_ROOT",
    "DIAMETER_FEATURE_COLUMNS",
    "DIAMETER_ZSCORE_COLUMNS",
    "FEATURE_COLUMNS_BY_VARIANT",
    "LEGACY_9_FEATURE_COLUMNS",
    "LEGACY_FEATURE_COLUMNS",
    "LEGACY_FILL_DEFAULTS",
    "MIN_TIME_SHIFT_S",
    "PRESSURE_FEATURE_COLUMNS",
    "PRESSURE_ZSCORE_COLUMNS",
    "PROJECT_ROOT",
    "REFERENCE_PRESSURE_BAR",
    "TARGET_SCALE_MODE_BY_VARIANT",
    "TIME_FEATURE",
    "ZSCORE_BASE_COLUMNS_BY_VARIANT",
    "resolve_tilt_angle_radian",
    "umbrella_to_tilt_radian",
    # data_io
    "DEFAULT_STAGE1_CONFIG",
    "DEFAULT_STAGE2_CONFIG",
    "DatasetMeta",
    "RunArtifacts",
    "Stage1Config",
    "Stage2Config",
    "StageTables",
    "build_dataset_registry",
    "merge_config",
    "normalize_dataset_key",
    # models
    "FamilyAwarePenetrationMLP",
    "FamilyFiLMAdapter",
    "PenetrationMLP",
    "RESIDUAL_FILM_ARCHITECTURE_MODES",
    "ResidualFamilyAwarePenetrationMLP",
    "ResidualFiLMFamilyAwarePenetrationMLP",
    "build_model",
    "family_head_state_dict_to_residual",
    "make_activation",
    "reconstruct_penetration_series",
    "sigmoid",
    "spray_penetration_model_sigmoid",
    "spray_penetration_model_sigmoid_d_dt",
    "state_dict_to_residual_film",
    # feature_engineering
    "NOZZLE_NAME_TO_ID",
    "REFERENCE_DENSITY_KG_M3",
    "apply_a_scale_transform",
    "apply_saved_scaler_state",
    "apply_zscore",
    "assign_splits_by_group",
    "assign_splits_leave_one_out",
    "build_all_stage_tables",
    "build_canonical_feature_table",
    "build_variant_feature_table",
    "build_sample_group_id",
    "canonicalize_chamber_state",
    "collect_selected_rows",
    "compute_a_scale",
    "family_id_from_name",
    "fit_zscore_params",
    "infer_dataset_name_from_csv_path",
    "infer_feature_family",
    "iter_clean_csv_files",
    "linear_density_from_pressure",
    "linear_pressure_from_density",
    "nozzle_id_from_name",
    "run_pretrain_collapse_check",
    "scaler_a_scale_dp_exp",
    "scaler_target_scale_mode",
    "select_filtered_rows",
    "select_representative_row",
    "variant_a_scale_dp_exp",
    "variant_target_scale_mode",
    # objectives
    "derivative_physics_penalty",
    "early_time_anchor_penalties",
    "onset_aux_penalty",
    "split_mu_logvar",
    "stage1_objective",
    "stage2_objective",
    # train_loop
    "PointwisePenetrationDataset",
    "collate_pointwise",
    "make_dataloaders",
    "run_epoch",
    "train_with_early_stopping",
    # checkpoint
    "create_run_dir",
    "plot_loss_curves",
    "sanitize_config_for_json",
    "save_training_outputs",
    # inference
    "build_feature_matrix_np",
    "build_feature_tensor_torch",
    "canonicalize_raw_input",
    "evaluate_physical_point_with_derivatives",
    "has_run_artifacts",
    "has_supported_checkpoint",
    "load_run_artifacts",
    "predict_physical_sweep",
    "resolve_model_path",
    "resolve_run_dir",
    "torch_scalar",
    "unwrap_state_dict",
    "zscore_from_state",
]
